Require "set" module in spec/parallel_tests/test/runner_spec.rb
Fixes the following failure when running the test in isolation:

    $ bundle exec rspec spec/parallel_tests/test/runner_spec.rb

    1) ParallelTests::Test::Runner.test_in_groups when passed runtime groups by size and uses specified groups of specs in specific order in specific processes
       Failure/Error: actual = groups.map(&:to_set).to_set

       NoMethodError:
         undefined method `to_set' for ["ddd", "eee"]:Array

                 actual = groups.map(&:to_set).to_set
                                ^^^^